// <auto-generated />
using System;
using CaseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaseTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221230053950_AddBlogCreatedTimestamp")]
    partial class AddBlogCreatedTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaseTracker.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<int>("CaseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DateOfArrival")
                        .HasColumnType("Date");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Survey")
                        .HasColumnType("int");

                    b.Property<string>("Workload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("engineerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("engineerId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CaseTracker.Models.SupporEngineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Engineer");
                });

            modelBuilder.Entity("CaseTracker.Models.Case", b =>
                {
                    b.HasOne("CaseTracker.Models.SupporEngineer", "engineer")
                        .WithMany("Cases")
                        .HasForeignKey("engineerId");
                });
#pragma warning restore 612, 618
        }
    }
}
